.TH dump_osc 1

.SH NAME
dump_osc \- Prints incoming OSC messages

.SH SYNOPSIS
.B dump_osc
\fIport\fP

.SH DESCRIPTION
.B dump_osc
prints all OSC messages received on \fIport\fP (UDP port number, or any other
address string supported by liblo).

.SH AUTHOR
Dominic Sacre <dominic.sacre@gmx.de>

.SH SEE ALSO
send_osc(1)
